### ISSUE TITLE
Show network name on hover

### ISSUE THREAD

**Issue by trajano** [mohsenasm/swarm-dashboard#16]
Can you show the network name as a tooltip when hovering over the lines?

**Comment by mohsenasm** [comment]
Merged with https://github.com/mohsenasm/swarm-dashboard/pull/27

**Comment by trajano** [comment]
Would this be in `:latest` soon? or does it need to be a specific label still?

**Comment by mohsenasm** [comment]
@trajano
Yeah. It's available as `mohsenasm/swarm-dashboard:latest` or `mohsenasm/swarm-dashboard:v2.0`
