### ISSUE TITLE
Showing resource usage of each container

### ISSUE THREAD

**Issue by holms** [mohsenasm/swarm-dashboard#18]
Just wondering is it technically possible? Because NexClipper does it, although it's only per host currently. I like you design lot more, and this would be a real killer feature. I might try to send PR if someone would provide at least small guideline :)

![screen](https://user-images.githubusercontent.com/280958/42617191-86ea82f6-85b9-11e8-8edf-2f5f8d2da217.png)

**Comment by mohsenasm** [comment]
Implemented and merged with https://github.com/mohsenasm/swarm-dashboard/pull/27

![swarm](https://github.com/mohsenasm/swarm-dashboard/assets/9164422/ca4b479b-17d7-4dc2-8746-74c020a1e2fb)
