### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by damnedOperator** [mohsenasm/swarm-dashboard#22]
Hi, SSL Support would be nice, as a deployment of the dashboard on an api host, reachable under a HSTS Domain won't be reachable because of HTTPS enforcement...

**Comment by PiecePaperCode** [comment]
I suggest putting the dashboard not on an exposed port. Instead use a reverse Proxy that enforces HTTPS like nginx and add some Auth in it.
Putting the Dashboard on an open internet port is not the way to go, because if it gets compromised your swarm gets taken over.

**Comment by mohsenasm** [comment]
Now we have this feature:
+ Using the `ENABLE_AUTHENTICATION` environment variable, there is an option to use `Basic Auth`. The WebSocket server will close the connection if it does not receive a valid authentication token.

+ Using the `ENABLE_HTTPS` environment variable, there is an option to use `HTTPS` and `WSS`. We have Let’s Encrypt integration with the DNS challenge using [Lego](https://go-acme.github.io/lego/dns/).
