### ISSUE TITLE
Show %CPU and %MEM for each node just below IP

### ISSUE THREAD

**Issue by flaviostutz** [mohsenasm/swarm-dashboard#24]
When looking at the dashboard and something is strange, I always have to look at the basic machine resources of each machine in order to verify if CPU and MEM are OK. Dashboard could just show this. 

Something like:

        server-m1              server-m2
         manager                manager
        10.120.0.5              10.120.0.6
      c:10% m:45%       c:97% m:35%
|------------------|------------------|

(with a smaller letter, we can use cpu:10% mem:35% too)

What do you think? I could work on that if needed...

**Comment by mohsenasm** [comment]
Implemented and merged with https://github.com/mohsenasm/swarm-dashboard/pull/27

![swarm](https://github.com/mohsenasm/swarm-dashboard/assets/9164422/ca4b479b-17d7-4dc2-8746-74c020a1e2fb)
