### ISSUE TITLE
Context root support

### ISSUE THREAD

**Issue by trajano** [mohsenasm/swarm-dashboard#28]
Can you make it so it works with a different context root e.g. `https://mysserver.com/swarm-dashboard` like the `CTX_ROOT` variable of swarm visualizer?

I think this may be [the solution](https://stackoverflow.com/a/70485006/242042)

**Comment by trajano** [comment]
Just tried to do it myself, failed miserably :P I am no nodeJS express dev that's for sure:

I started with
```
/**
 * The context root of the web application.
 * @type {string}
 */
const contextRoot = process.env.CTX_ROOT || "/";
```

But I can't seem to figure out how to link

```
const router = express.Router()
app.use(contextRoot, router)
```
with the new path.

**Comment by mohsenasm** [comment]
I just added this feature with env var `PATH_PREFIX`.
Could you check it?
Docker image: `mohsenasm/swarm-dashboard:dev_path_prefix`

**Comment by trajano** [comment]
Yup looks good.  I was reading up on how to code in elm for this last bit to get the variable

```
localWebsocket location =
    if location.protocol == "https:" then
        "wss://" ++ location.host ++ "/stream"
    else
        "ws://" ++ location.host ++ "/stream"
```

But you beat me to it :D

**Comment by trajano** [comment]
So can we have a `v2.1` soon?

**Comment by mohsenasm** [comment]
Yeah, `v2.1` is available now.
