### ISSUE TITLE
API endpoint for fetching the lastData objecct

### ISSUE THREAD

**Issue by Josh5** [mohsenasm/swarm-dashboard#39]
Would it be possible to add some URL that could be fetched from an external tool to check the details of the swarm using the JSON object?

Something like `/status` which would return the `lastData` object that is normally streamed with the WS.

**Comment by mohsenasm** [comment]
Hi @Josh5 

I have added the `/data` API.
You can now use it with the docker image `mohsenasm/swarm-dashboard:dev_data_api`.
Note that you need to enable this API by setting the `ENABLE_DATA_API` environment variable to `true`.

**Comment by Josh5** [comment]
> Hi @Josh5 
> 
> I have added the `/data` API.
> You can now use it with the docker image `mohsenasm/swarm-dashboard:dev_data_api`.
> Note that you need to enable this API by setting the `ENABLE_DATA_API` environment variable to `true`.

Legend! Thanks
